import Link from "next/link";
import Image from "next/image";
import { notFound } from "next/navigation";

import { AdminMediaUploader } from "@/components/admin-media-uploader";
import { ConfirmSubmitButton } from "@/components/confirm-submit-button";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { getAdminCatalog, getAdminProduct } from "@/lib/admin-catalog";
import { isSupabaseStorageConfigured } from "@/lib/supabase-admin";
import { addProductImageAction, addVariantAction, archiveProductAction, attachTagAction, deleteProductAction, deleteProductImageAction, deleteVariantAction, detachTagAction, updateProductAction, updateProductCollectionsAction, updateProductImageAction, updateVariantAction } from "../actions";

type Props = { params: Promise<{ productId: string }> };

export const metadata = { title: "Edit product | Admin" };

export default async function AdminProductPage({ params }: Props) {
  const { productId } = await params;
  const [product, catalog] = await Promise.all([getAdminProduct(productId), getAdminCatalog()]);
  if (!product) notFound();
  const availableTags = catalog.tags.filter((tag) => !product.tags.some((current) => current.id === tag.id));
  const uploadsEnabled = isSupabaseStorageConfigured();
  return <section>
    <Link href="/admin/catalog" className="text-sm text-muted-foreground hover:text-foreground">← Catalog</Link>
    <div className="mt-4 flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[.2em] text-muted-foreground">Product editor</p><h2 className="mt-2 font-heading text-5xl">{product.title}</h2></div><Badge variant="outline" className="rounded-none">{product.status.toLowerCase()}</Badge></div>
    <div className="mt-8 grid gap-6 xl:grid-cols-[minmax(0,1.2fr)_minmax(20rem,.8fr)]">
      <Card className="rounded-none"><CardHeader><CardTitle className="font-heading text-3xl">Details</CardTitle></CardHeader><CardContent><form action={updateProductAction.bind(null, product.id)} className="grid gap-4 sm:grid-cols-2">
        <div className="grid gap-1.5"><Label htmlFor="edit-title">Title</Label><Input id="edit-title" name="title" defaultValue={product.title} required /></div><div className="grid gap-1.5"><Label htmlFor="edit-slug">Slug</Label><Input id="edit-slug" name="slug" defaultValue={product.slug} required /></div>
        <div className="sm:col-span-2"><Label htmlFor="edit-description">Description</Label><Textarea id="edit-description" name="description" defaultValue={product.description} required /></div>
        <div className="grid gap-1.5"><Label htmlFor="edit-category">Category</Label><select id="edit-category" name="categoryId" defaultValue={product.categoryId} className="h-10 w-full border bg-background px-3 text-sm">{catalog.categories.map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select></div><div className="grid gap-1.5"><Label htmlFor="edit-status">Status</Label><select id="edit-status" name="status" defaultValue={product.status} className="h-10 w-full border bg-background px-3 text-sm"><option>DRAFT</option><option>ACTIVE</option><option>ARCHIVED</option></select></div>
        <div className="grid gap-1.5"><Label htmlFor="edit-price">Price</Label><Input id="edit-price" name="price" type="number" step=".01" min=".01" defaultValue={Number(product.price)} required /></div><div className="grid gap-1.5"><Label htmlFor="edit-compare">Compare at</Label><Input id="edit-compare" name="compareAtPrice" type="number" step=".01" min="0" defaultValue={product.compareAtPrice ? Number(product.compareAtPrice) : ""} /></div>
        <div className="grid gap-1.5"><Label htmlFor="edit-sku">Base SKU</Label><Input id="edit-sku" name="sku" defaultValue={product.sku ?? ""} /></div><div className="grid gap-1.5"><Label htmlFor="edit-stock">Total stock</Label><Input id="edit-stock" name="stockQuantity" type="number" min="0" defaultValue={product.stockQuantity} required /></div>
        <div className="grid gap-1.5"><Label htmlFor="edit-threshold">Low-stock threshold</Label><Input id="edit-threshold" name="lowStockThreshold" type="number" min="0" defaultValue={product.lowStockThreshold} required /></div><label className="flex items-end gap-2 pb-2 text-sm"><input name="isFeatured" type="checkbox" defaultChecked={product.isFeatured} /> Featured</label>
        <Button className="rounded-none sm:col-span-2">Save product</Button>
      </form><form action={archiveProductAction.bind(null, product.id)} className="mt-3"><Button variant="outline" className="w-full rounded-none" disabled={product.status === "ARCHIVED"}>Archive product</Button></form><form action={deleteProductAction.bind(null, product.id)} className="mt-3"><ConfirmSubmitButton message={product._count.orderItems ? "This product has order history, so it will be archived instead of permanently deleted. Continue?" : "Permanently delete this product, its variants, and its images?"}>{product._count.orderItems ? "Archive historical product" : "Delete product"}</ConfirmSubmitButton></form></CardContent></Card>

      <div className="space-y-6">
        <Card className="rounded-none"><CardHeader><CardTitle className="font-heading text-3xl">Variants & inventory</CardTitle></CardHeader><CardContent><ul className="space-y-3">{product.variants.map((variant) => <li key={variant.id} className="border p-3"><form action={updateVariantAction.bind(null, product.id, variant.id)} className="grid gap-2 sm:grid-cols-2"><Input name="title" defaultValue={variant.title} aria-label="Variant title" required /><Input name="sku" defaultValue={variant.sku} aria-label="Variant SKU" required /><Input name="color" defaultValue={variant.color ?? ""} aria-label="Color" placeholder="Color" /><Input name="colorHex" defaultValue={variant.colorHex ?? ""} aria-label="Color hex" placeholder="#681321" /><Input name="size" defaultValue={variant.size ?? ""} aria-label="Size" placeholder="Size" /><Input name="stockQuantity" type="number" min="0" defaultValue={variant.stockQuantity} aria-label="Stock" required /><Input name="price" type="number" min="0" step=".01" defaultValue={variant.price ? Number(variant.price) : ""} placeholder="Override price" aria-label="Override price" className="sm:col-span-2" /><Button size="sm" variant="outline" className="rounded-none sm:col-span-2">Save variant</Button></form>{variant._count.orderItems ? <p className="mt-2 text-xs text-muted-foreground">Used in {variant._count.orderItems} order item(s); set stock to zero instead of deleting.</p> : <form action={deleteVariantAction.bind(null, product.id, variant.id)} className="mt-2"><ConfirmSubmitButton message={`Delete variant “${variant.title}”?`}>Delete variant</ConfirmSubmitButton></form>}</li>)}</ul>
          <form action={addVariantAction.bind(null, product.id)} className="mt-5 grid gap-3 border-t pt-5 sm:grid-cols-2"><Input name="title" placeholder="Title" required /><Input name="sku" placeholder="SKU" required /><Input name="color" placeholder="Color" /><Input name="colorHex" placeholder="#681321" /><Input name="size" placeholder="Size" /><Input name="stockQuantity" type="number" min="0" defaultValue="0" required /><Input name="price" type="number" min="0" step=".01" placeholder="Override price" className="sm:col-span-2" /><Button className="rounded-none sm:col-span-2">Add variant</Button></form>
        </CardContent></Card>
        <Card className="rounded-none"><CardHeader><CardTitle className="font-heading text-3xl">Images & tags</CardTitle></CardHeader><CardContent><ul className="grid gap-3">{product.images.map((image) => <li key={image.id} className="border p-3"><div className="relative mb-3 aspect-[3/4] max-w-40 overflow-hidden bg-muted"><Image src={image.url} alt="" fill sizes="160px" className="object-cover" /></div><form action={updateProductImageAction.bind(null, product.id, image.id)} className="grid gap-2 sm:grid-cols-[minmax(0,1fr)_5rem]"><Input name="altText" defaultValue={image.altText ?? product.title} aria-label="Image alt text" placeholder="Alt text" /><Input name="displayOrder" type="number" min="0" defaultValue={image.displayOrder} aria-label="Display order" /><label className="flex items-center gap-2 text-sm sm:col-span-2"><input type="checkbox" name="isPrimary" defaultChecked={image.isPrimary} /> Primary image</label><Button variant="outline" size="sm" className="rounded-none sm:col-span-2">Save image</Button></form><form action={deleteProductImageAction.bind(null, product.id, image.id)} className="mt-2"><ConfirmSubmitButton message="Remove this image from the product? The uploaded media file will remain in the media library.">Remove image</ConfirmSubmitButton></form></li>)}</ul><form action={addProductImageAction.bind(null, product.id)} className="mt-4 grid gap-3"><AdminMediaUploader enabled={uploadsEnabled} fieldName="url" label="product images" defaultAltText={product.title} /><Button className="rounded-none">Attach uploaded images</Button></form>
          <div className="mt-5 flex flex-wrap gap-2">{product.tags.map((tag) => <form key={tag.id} action={detachTagAction.bind(null, product.id, tag.id)}><Button type="submit" variant="outline" size="sm" className="rounded-none" aria-label={`Remove ${tag.name} tag`}>{tag.name} ×</Button></form>)}</div>{availableTags.length ? <form action={attachTagAction.bind(null, product.id)} className="mt-3 flex gap-2"><select name="tagId" className="h-10 min-w-0 flex-1 border bg-background px-3 text-sm">{availableTags.map((tag) => <option key={tag.id} value={tag.id}>{tag.name}</option>)}</select><Button variant="outline" className="rounded-none">Attach</Button></form> : null}
        </CardContent></Card>
        <Card className="rounded-none"><CardHeader><CardTitle className="font-heading text-3xl">Collections</CardTitle></CardHeader><CardContent><form action={updateProductCollectionsAction.bind(null, product.id)} className="grid gap-3">{catalog.collections.map((collection) => <label key={collection.id} className="flex items-center gap-2 text-sm"><input type="checkbox" name="collectionIds" value={collection.id} defaultChecked={product.collections.some((current) => current.id === collection.id)} /> {collection.name}</label>)}<Button variant="outline" className="mt-2 rounded-none">Save collections</Button></form></CardContent></Card>
      </div>
    </div>
  </section>;
}
