import { notFound } from "next/navigation";
import { getAdminOrder } from "@/lib/admin-orders";
import { formatEgp } from "@/lib/storefront";

type Props = { params: Promise<{ orderId: string }> };

export default async function PrintableOrderPage({ params }: Props) {
  const { orderId } = await params; const order = await getAdminOrder(orderId); if (!order) notFound();
  const address = order.shippingAddress as Record<string, string | null>;
  return <><style>{"@media print { body > header, body > footer, aside, nav { display: none !important; } body { background: white !important; } }"}</style><main className="mx-auto max-w-4xl bg-white p-10 text-black"><header className="flex justify-between border-b border-black pb-6"><div><p className="font-heading text-4xl">Talié</p><p className="text-sm">Order document</p></div><div className="text-right"><h1 className="text-xl font-semibold">{order.orderNumber}</h1><p className="text-sm">{order.createdAt.toLocaleString("en-EG")}</p></div></header><section className="grid grid-cols-2 gap-8 py-6 text-sm"><div><h2 className="font-semibold">Customer</h2><p>{order.customerName}</p><p>{order.customerEmail}</p><p>{order.customerPhone}</p></div><div><h2 className="font-semibold">Ship to</h2><p>{address.street}{address.apartment ? `, ${address.apartment}` : ""}</p><p>{address.city}, {address.governorate}</p><p>{address.country}</p></div></section><table className="w-full text-left text-sm"><thead className="border-y border-black"><tr><th className="py-3">Item</th><th>Qty</th><th>Price</th><th className="text-right">Total</th></tr></thead><tbody>{order.items.map((item) => <tr key={item.id} className="border-b"><td className="py-3">{item.title}<br /><span className="text-xs">{item.variantTitle}</span></td><td>{item.quantity}</td><td>{formatEgp(Number(item.price))}</td><td className="text-right">{formatEgp(Number(item.total))}</td></tr>)}</tbody></table><dl className="ml-auto mt-6 w-72 space-y-2 text-sm"><div className="flex justify-between"><dt>Subtotal</dt><dd>{formatEgp(Number(order.subtotal))}</dd></div><div className="flex justify-between"><dt>Discount{order.discountCode ? ` · code ${order.discountCode} (−${formatEgp(Number(order.couponDiscount))})` : ""}</dt><dd>− {formatEgp(Number(order.discount))}</dd></div><div className="flex justify-between"><dt>Shipping</dt><dd>{formatEgp(Number(order.shippingCost))}</dd></div><div className="flex justify-between border-t border-black pt-2 font-semibold"><dt>Total</dt><dd>{formatEgp(Number(order.total))}</dd></div></dl></main></>;
}
