import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { getAdminAnalytics } from "@/lib/admin-operations";
import { formatEgp } from "@/lib/storefront";

export const metadata = { title: "Analytics | Admin" };

export default async function AdminAnalyticsPage() {
  const data = await getAdminAnalytics();
  const peak = Math.max(1, ...data.months.map((month) => month.revenue));
  return <section><p className="text-xs font-semibold uppercase tracking-[.2em] text-muted-foreground">Insights</p><h2 className="mt-3 font-heading text-5xl">Analytics</h2><div className="mt-8 grid gap-4 sm:grid-cols-3"><Card className="rounded-none"><CardHeader><CardTitle className="text-sm text-muted-foreground">12-month paid revenue</CardTitle></CardHeader><CardContent className="font-heading text-4xl">{formatEgp(data.paidRevenue)}</CardContent></Card><Card className="rounded-none"><CardHeader><CardTitle className="text-sm text-muted-foreground">Customers</CardTitle></CardHeader><CardContent className="font-heading text-4xl">{data.customerCount}</CardContent></Card><Card className="rounded-none"><CardHeader><CardTitle className="text-sm text-muted-foreground">Paying customers</CardTitle></CardHeader><CardContent className="font-heading text-4xl">{data.payingCustomers}</CardContent></Card></div><div className="mt-4 flex flex-wrap gap-2">{data.orderStatuses.map((status) => <span key={status.status} className="border px-3 py-1 text-xs uppercase tracking-wider">{status.status.toLowerCase()} · {status._count._all}</span>)}</div><div className="mt-6 grid gap-6 xl:grid-cols-[1.4fr_.8fr]"><Card className="rounded-none"><CardHeader><CardTitle className="font-heading text-3xl">Revenue trend</CardTitle></CardHeader><CardContent><div className="flex h-64 items-end gap-2" aria-label="Monthly paid revenue">{data.months.map((month) => <div key={month.label} className="flex min-w-0 flex-1 flex-col items-center gap-2"><div className="w-full bg-primary/80" style={{ height: `${Math.max(3, month.revenue / peak * 190)}px` }} title={`${month.label}: ${formatEgp(month.revenue)}`} /><span className="text-[.6rem] text-muted-foreground [writing-mode:vertical-rl]">{month.label}</span></div>)}</div></CardContent></Card><Card className="rounded-none"><CardHeader><CardTitle className="font-heading text-3xl">Top products</CardTitle></CardHeader><CardContent><ol className="divide-y">{data.topItems.map((item) => <li key={item.productId} className="flex justify-between gap-4 py-3"><span>{item.title}</span><span className="text-muted-foreground">{item._sum.quantity ?? 0} sold</span></li>)}</ol>{!data.topItems.length ? <p className="text-sm text-muted-foreground">No paid sales yet.</p> : null}</CardContent></Card></div></section>;
}
